
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.*;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Time;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PARUL
 */
public class seeker extends javax.swing.JFrame {

   private int sid;
    private Connection conn;  
    private Statement stmt;
    private ResultSet rs,rs1,rs2,rs4;
    private String username="root";
    private String dbName="proj1";
    private String password="";
     String driverName="com.mysql.jdbc.Driver";
     String a,b,c;
private String dbURL="jdbc:mysql://localhost:3306/"+dbName;

       

    /**
     * Creates new form signup
     */
      
/**
     * Creates new form seeker
     */
    public seeker(int sid) {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        this.sid=sid;
        try {
            conn=DriverManager.getConnection(dbURL,username,password);
            stmt=conn.createStatement();
        } catch (SQLException ex) {
            //Logger.getLogger(studentlogic.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Exception "+ex);
        }
        
    }
    public seeker(){
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        label = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        destination_field = new javax.swing.JComboBox<>();
        pMOT_field = new javax.swing.JComboBox<>();
        male_field = new javax.swing.JRadioButton();
        female_field = new javax.swing.JRadioButton();
        any_field = new javax.swing.JRadioButton();
        hour_field = new javax.swing.JComboBox<>();
        minute_field = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        label.setText("Where do you want to go?");
        jPanel3.add(label);
        label.setBounds(10, 10, 160, 14);

        jLabel1.setText("Preferred mode of transportation");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(10, 50, 230, 14);

        jLabel2.setText("Gender Prefernce");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(10, 100, 160, 14);

        destination_field.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ghuma Gam", "Iskon Cross Road", "Shivranjani", "Nehrunagar", "Anjai", "Vasna", "Narol", "Maninagar", "Hatkeshwar", "S.P. Ring Road", "Kalupur Railway Station", "Commerce Six Road", "M.J. Library", "RTO Circle", "Zundal Circle", "Sola Bhagwat", "Science City Approach" }));
        destination_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destination_fieldActionPerformed(evt);
            }
        });
        jPanel3.add(destination_field);
        destination_field.setBounds(210, 10, 138, 20);

        pMOT_field.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2 - wheeler", "3 - wheeler", "4 - wheeler", "BRTS", "AMTS", "Any" }));
        pMOT_field.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pMOT_fieldMouseClicked(evt);
            }
        });
        pMOT_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pMOT_fieldActionPerformed(evt);
            }
        });
        pMOT_field.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                pMOT_fieldPropertyChange(evt);
            }
        });
        jPanel3.add(pMOT_field);
        pMOT_field.setBounds(210, 50, 120, 20);

        male_field.setBackground(new java.awt.Color(255, 255, 255));
        bg.add(male_field);
        male_field.setText("Male");
        jPanel3.add(male_field);
        male_field.setBounds(220, 90, 80, 23);

        female_field.setBackground(new java.awt.Color(255, 255, 255));
        bg.add(female_field);
        female_field.setText("Female");
        female_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                female_fieldActionPerformed(evt);
            }
        });
        jPanel3.add(female_field);
        female_field.setBounds(220, 120, 80, 23);

        any_field.setBackground(new java.awt.Color(255, 255, 255));
        bg.add(any_field);
        any_field.setText("Any");
        any_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                any_fieldActionPerformed(evt);
            }
        });
        jPanel3.add(any_field);
        any_field.setBounds(220, 150, 80, 23);

        hour_field.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));
        hour_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hour_fieldActionPerformed(evt);
            }
        });
        jPanel3.add(hour_field);
        hour_field.setBounds(200, 200, 50, 20);

        minute_field.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "05", "10", "15", "20", "25", "30", "35", "40", "45", "50", "55", "60" }));
        jPanel3.add(minute_field);
        minute_field.setBounds(270, 200, 50, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Departure Time");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(10, 200, 140, 15);

        jLabel7.setText("Hours");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(200, 180, 50, 14);

        jLabel8.setText("Minutes");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(270, 180, 60, 14);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(20, 10, 350, 230);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Ride Now");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(160, 250, 100, 40);

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Back");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(160, 300, 100, 23);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Algerian", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Seeker1.jpg"))); // NOI18N
        jPanel2.add(jLabel3);
        jLabel3.setBounds(40, 30, 120, 49);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seeker3.jpg"))); // NOI18N
        jPanel2.add(jLabel4);
        jLabel4.setBounds(40, 100, 120, 120);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 16, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void female_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_female_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_female_fieldActionPerformed

    private void destination_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destination_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_destination_fieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//connection c3=new connection();
String destination=destination_field.getSelectedItem().toString();
String pMOT=pMOT_field.getSelectedItem().toString();
//int seatAvailable=Integer.parseInt((String) seatAvailable_field.getSelectedItem()) ;
//String vehicleNo=vehicleno_field.getText();
String hours=hour_field.getSelectedItem().toString();
String minutes=minute_field.getSelectedItem().toString();
//String second="00";
String timer=hours+":"+minutes+":00";
//T timer=
Time lt=Time.valueOf(timer);
String genderP = null;

if(male_field.isSelected()){
    genderP=male_field.getText();
}
if(female_field.isSelected()){
    genderP=female_field.getText();
}
if(any_field.isSelected()){
    genderP=any_field.getText();
}
 String insertQuery = "INSERT INTO `seeker`(`sid`,`destination`, `pMOT`,  `genderP`,`time`) VALUES ("+sid+",'" + destination + "','" + pMOT + "','" + genderP + "','"+lt+"')";

        // ="INSERT INTO `login`" + "VALUES ('" + email_id + "'," +pass+")";
        System.out.println("insertQuery= " + insertQuery);
        try {
            int result = stmt.executeUpdate(insertQuery);
//            if (result == 1) {
//                
//            }

        } catch (SQLException ex) {
            // Logger.getLogger(studentlogic.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Exception " + ex);
        }
        

//if(c3.addSeeker( destination, pMOT,  genderP)){
//    int dialogType=JOptionPane.INFORMATION_MESSAGE;
//JOptionPane.showMessageDialog(null, "Succesfully Added", "Seeker Added", dialogType);
//        }
//    else
//{int dialogType=JOptionPane.ERROR_MESSAGE;
//
//// TODO add your handling code here:
//    }
//try{
//    
// String iQ="INSERT INTO `helper`(`ID`) VALUES (" +ID+ ")";
// }catch(Exception e){
//         System.out.println(e);
//         }

    
match sign = null;
       try {
           sign = new match(sid,destination,genderP,pMOT,lt);
       } catch (ParseException ex) {
          // Logger.getLogger(seeker.class.getName()).log(Level.SEVERE, null, ex);
       }
//       if(sign.helperList.size()==0){
//           
//       }
        sign.setVisible(true);
        sign.pack();
        sign.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();     
        
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void pMOT_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pMOT_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pMOT_fieldActionPerformed

    private void any_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_any_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_any_fieldActionPerformed

    private void pMOT_fieldPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_pMOT_fieldPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_pMOT_fieldPropertyChange

    private void pMOT_fieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pMOT_fieldMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pMOT_fieldMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
user mm=new user(sid);
        mm.setVisible(true);
        mm.pack();
        mm.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();          // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void hour_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hour_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hour_fieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(seeker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(seeker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(seeker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(seeker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new seeker().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton any_field;
    private javax.swing.ButtonGroup bg;
    private javax.swing.JComboBox<String> destination_field;
    private javax.swing.JRadioButton female_field;
    private javax.swing.JComboBox<String> hour_field;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel label;
    private javax.swing.JRadioButton male_field;
    private javax.swing.JComboBox<String> minute_field;
    private javax.swing.JComboBox<String> pMOT_field;
    // End of variables declaration//GEN-END:variables
}
