//import javafx.*;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;



/**
 *
 * @author PARUL
 * 
 */


    

public class signup extends javax.swing.JFrame {
   
    int ID;
    private Connection conn;  
    private Statement stmt;
    private ResultSet rs,rs1,rs2,rs4;
    private String username="root";
    private String dbName="proj1";
    private String password="";
     String driverName="com.mysql.jdbc.Driver";
     String a,b,c;
private String dbURL="jdbc:mysql://localhost:3306/"+dbName;

       

    /**
     * Creates new form signup
     */
    public signup() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
         try {
            conn=DriverManager.getConnection(dbURL,username,password);
            stmt=conn.createStatement();
        } catch (SQLException ex) {
            //Logger.getLogger(studentlogic.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Exception "+ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSlider1 = new javax.swing.JSlider();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nameF = new javax.swing.JTextField();
        rnF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        c_passwordF = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        passwordF = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        residenceF = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        vehicle_noF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        MOTF = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        contactnoF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ageF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        maleF = new javax.swing.JRadioButton();
        femaleF = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        emailF = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Algerian", 0, 48)); // NOI18N
        jLabel10.setText("Sign up");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(100, 210, 180, 64);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/signup.png"))); // NOI18N
        jPanel2.add(jLabel13);
        jLabel13.setBounds(150, 290, 80, 110);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(null);

        jLabel14.setFont(new java.awt.Font("Algerian", 0, 48)); // NOI18N
        jLabel14.setText("Sign up");
        jPanel4.add(jLabel14);
        jLabel14.setBounds(90, 280, 180, 64);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/signup.png"))); // NOI18N
        jPanel4.add(jLabel15);
        jLabel15.setBounds(130, 370, 80, 110);

        jPanel2.add(jPanel4);
        jPanel4.setBounds(0, 0, 0, 0);

        jLabel16.setText("Use Sign Up for capture your users");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(90, 460, 200, 20);

        jLabel17.setText(" information for Helping and seeking.");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(90, 510, 240, 14);

        jPanel3.setBackground(new java.awt.Color(102, 102, 255));
        jPanel3.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setText("Name");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(68, 11, 100, 14);

        nameF.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        nameF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFActionPerformed(evt);
            }
        });
        jPanel1.add(nameF);
        nameF.setBounds(70, 30, 190, 20);

        rnF.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(rnF);
        rnF.setBounds(70, 90, 190, 20);

        jLabel2.setText("Roll Number");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(68, 68, 130, 20);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(70, 52, 190, 2);

        jLabel12.setText("Confirm Password");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(70, 520, 130, 14);

        c_passwordF.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(c_passwordF);
        c_passwordF.setBounds(70, 540, 190, 20);

        jLabel11.setText("Password");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(70, 470, 130, 14);

        passwordF.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        passwordF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFActionPerformed(evt);
            }
        });
        jPanel1.add(passwordF);
        passwordF.setBounds(70, 490, 190, 20);

        jLabel9.setText("Residence");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(70, 420, 110, 14);

        residenceF.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(residenceF);
        residenceF.setBounds(70, 440, 190, 20);

        jLabel8.setText("Vehicle Info");
        jLabel8.setEnabled(false);
        jPanel1.add(jLabel8);
        jLabel8.setBounds(70, 370, 130, 14);

        vehicle_noF.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        vehicle_noF.setEnabled(false);
        vehicle_noF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehicle_noFActionPerformed(evt);
            }
        });
        jPanel1.add(vehicle_noF);
        vehicle_noF.setBounds(70, 390, 190, 20);

        jLabel7.setText("Ganeral mode of transportation");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(70, 320, 210, 14);

        MOTF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2 - wheeler", "3 - wheeler", "4 - wheeler", "BRTS", "AMTS", "Pedestrian" }));
        MOTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MOTFActionPerformed(evt);
            }
        });
        jPanel1.add(MOTF);
        MOTF.setBounds(70, 340, 150, 20);

        jLabel6.setText("Contact Number");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(70, 270, 130, 14);

        contactnoF.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        contactnoF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactnoFActionPerformed(evt);
            }
        });
        jPanel1.add(contactnoF);
        contactnoF.setBounds(70, 290, 190, 20);

        jLabel5.setText("Age");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(70, 220, 80, 14);

        ageF.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ageF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageFActionPerformed(evt);
            }
        });
        jPanel1.add(ageF);
        ageF.setBounds(70, 240, 190, 20);

        jLabel4.setText("Gender");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(70, 170, 130, 14);

        maleF.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(maleF);
        maleF.setText("Male");
        jPanel1.add(maleF);
        maleF.setBounds(70, 190, 70, 23);

        femaleF.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(femaleF);
        femaleF.setText("Female");
        jPanel1.add(femaleF);
        femaleF.setBounds(170, 190, 90, 23);

        jLabel3.setText("Emai ID");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(70, 120, 120, 14);

        emailF.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(emailF);
        emailF.setBounds(70, 140, 190, 20);
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(70, 110, 190, 2);
        jPanel1.add(jSeparator3);
        jSeparator3.setBounds(70, 164, 190, 2);
        jPanel1.add(jSeparator4);
        jSeparator4.setBounds(70, 262, 190, 2);
        jPanel1.add(jSeparator6);
        jSeparator6.setBounds(70, 350, 130, 0);
        jPanel1.add(jSeparator7);
        jSeparator7.setBounds(70, 310, 190, 2);
        jPanel1.add(jSeparator8);
        jSeparator8.setBounds(70, 410, 190, 2);
        jPanel1.add(jSeparator9);
        jSeparator9.setBounds(70, 460, 190, 2);
        jPanel1.add(jSeparator10);
        jSeparator10.setBounds(70, 510, 190, 2);
        jPanel1.add(jSeparator11);
        jSeparator11.setBounds(70, 560, 190, 2);

        jPanel3.add(jPanel1);
        jPanel1.setBounds(40, 40, 310, 570);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/right1.jpg"))); // NOI18N
        jButton1.setText("Done");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(50, 620, 100, 40);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/right.jpg"))); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(230, 620, 100, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ageFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageFActionPerformed

    private void contactnoFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactnoFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactnoFActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        connection c1=new connection();
         //vehicle_noF.setEnabled(false);
        String ab=ageF.getText();
String cn1=contactnoF.getText();
if(ab.equals("") || cn1.equals("")){
    JOptionPane.showMessageDialog(null, "Some fileds might be empty");
}else{
String name=nameF.getText();
String rollno=rnF.getText();
String email_id=emailF.getText();

//if(maleF.get)
String gender=null;
if(maleF.isSelected()){
         gender=maleF.getText();}
else if(femaleF.isSelected()){
    gender=femaleF.getText();
}
else {
    gender="";
}

int age=Integer.parseInt(ageF.getText());
 



long contactno=Long.parseLong(contactnoF.getText());
//long cn = (long) Math.log10(contactno) + 1;
//String cn1=contactnoF.getText();
String uMOT=MOTF.getSelectedItem().toString();
if(uMOT.equals("BRTS")){
    jLabel8.setEnabled(true);
}
   
//}
String vehicle_no=vehicle_noF.getText();
String residence=residenceF.getText();
String password=passwordF.getText();
String c_password=c_passwordF.getText();
//if (!(Pattern.matches("^[a-zA-Z0-9]+[@]{1}+[a-zA-Z0-9]+[.]{1}+[a-zA-Z0-9]+$", email_id))) 
//{
//            JOptionPane.showMessageDialog(null, "Please enter a valid email", "Error", JOptionPane.ERROR_MESSAGE);
//            }
//            else
//            {
//                JOptionPane.showMessageDialog(null, "The email is valid", "Good!", JOptionPane.INFORMATION_MESSAGE);
//
//            }
if(name.equals("")|| rollno.equals("")|| email_id.equals("")||gender.compareTo("")==0|| uMOT.equals("")||  residence.equals("")||password.equals("")|| c_password.equals("")){
        //|| rollno || email_id || gender ||  MOT || vehicle_no || residence || password || c_password == null){
  JOptionPane.showMessageDialog(null, "Some fileds might be empty");
}
else if (!(Pattern.matches("^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@((\\[[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\])|(([a-zA-Z\\-0-9]+\\.)+[a-zA-Z]{2,}))$", email_id))) 
{
            JOptionPane.showMessageDialog(null, "Please enter a valid email", "Error", JOptionPane.ERROR_MESSAGE);
           }
else if(!(password.matches(".*[0-9]{1,}.*") && password.matches(".*[@#$]{1,}.*") && password.length()>=6 && password.length()<=20)){
    JOptionPane.showMessageDialog(null, "Password should contains atleast 6 letters and must have atleast one digit and one special character(@, #, $)", "Error", JOptionPane.ERROR_MESSAGE);
}
else{
//    if (!(Pattern.matches("^[a-zA-Z0-9]+[@]{1}+[a-zA-Z0-9]+[.]{1}+[a-zA-Z0-9]+$", email_id))) 
//{
//            JOptionPane.showMessageDialog(null, "Please enter a valid email", "Error", JOptionPane.ERROR_MESSAGE);
//            }
//            else
//            {
//                JOptionPane.showMessageDialog(null, "The email is valid", "Good!", JOptionPane.INFORMATION_MESSAGE);
//
//            }
if(password.equals(c_password)){
if(c1.addSignup(name, rollno,email_id, gender, age, contactno, uMOT, vehicle_no, residence,password, c_password)){
    int dialogType=JOptionPane.INFORMATION_MESSAGE;
//    try{
//     String eQ="SELECT ID FROM `signup` WHERE `email_id` LIKE '"+email_id+"'";
//     rs4=stmt.executeQuery(eQ);
//     while(rs4.next()){
//    ID=rs4.getInt(1);
//         }
// System.out.println(ID);
// }catch(Exception e){
//         System.out.println(e);
//         }
JOptionPane.showMessageDialog(null, "Succesfully Added", "New User Added", dialogType);}
    else
{int dialogType=JOptionPane.ERROR_MESSAGE;

// TODO add your handling code here:
    }        
      // int ID=;
       
       logins u=new logins();
        u.setVisible(true);
        u.pack();
        u.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
    else
    {
        int dialogType=JOptionPane.ERROR_MESSAGE;
        JOptionPane.showMessageDialog(null, "Password and confirm password not matched", "Error", dialogType);
    }
    }
    }
   
    }

//    public int getID() {
//        return ID;
//    }
//
//    public void setID(int ID) {
//        this.ID = ID;
//    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
main_menu mm=new main_menu();
        mm.setVisible(true);
        mm.pack();
        mm.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void MOTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MOTFActionPerformed
String a=MOTF.getSelectedItem().toString();
if(a.equals("2 - wheeler") ||a.equals("4 - wheeler")){
    jLabel8.setEnabled(true);
    vehicle_noF.setEnabled(true);
}else{
    jLabel8.setEnabled(false);
    vehicle_noF.setEnabled(false);
}
// TODO add your handling code here:
    }//GEN-LAST:event_MOTFActionPerformed

    private void nameFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFActionPerformed

    private void passwordFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFActionPerformed

    private void vehicle_noFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicle_noFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vehicle_noFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> MOTF;
    private javax.swing.JTextField ageF;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPasswordField c_passwordF;
    private javax.swing.JTextField contactnoF;
    private javax.swing.JTextField emailF;
    private javax.swing.JRadioButton femaleF;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JRadioButton maleF;
    private javax.swing.JTextField nameF;
    private javax.swing.JPasswordField passwordF;
    private javax.swing.JTextField residenceF;
    private javax.swing.JTextField rnF;
    private javax.swing.JTextField vehicle_noF;
    // End of variables declaration//GEN-END:variables
}
